# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webseite der deutschsprachigen Mathematikfachschaften
email: homepage@die-koma.org
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://die-koma.org" # the base hostname & protocol for your site
github_username:  Die-KoMa

# exclude local gem folder
exclude: ['ruby-packages']

# Build settings
markdown: kramdown

# Remove .html from generated website as https://jekyllrb.com/docs/permalinks/#posts suggests
permalink: pretty

# Defaults, mainly to set a layout
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      menuentry: true
      submenu: true
