name: 'Update next-koma.json'

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch: {}

jobs:
  update-next-koma:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update from the wiki
        run: python fetch-next-koma.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Sync next-koma.json from wiki
          branch: update-next-koma-json
          delete-branch: true
          title: 'Update next-koma.json'
          body: |
            This is an automatically created PR.

            The contents of `next-koma.json` was taken from the wiki.
          labels: |
            automated pr
